FROM wordpress:5.0.3

RUN apt-get update && apt-get install -y curl

RUN curl -L -o ~/phpunit.phar https://phar.phpunit.de/phpunit-4.8.phar \
  && chmod +x ~/phpunit.phar \
  && mv ~/phpunit.phar /usr/local/bin/phpunit
