version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data-local:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: docker-press:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8088:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

volumes:
  db-data-local:
